clc; 
clear all; 
close all; 
warning off;



load 8psk_zf.mat
plot(SNRs(:,1:20),datarate(1:20,:),'-b>',...
    'LineWidth',1,...
    'MarkerSize',6,...
    'MarkerEdgeColor','k',...
    'MarkerFaceColor',[0.9,0.9,0.0]);
hold on

load Qpsk_TWH_alpha=0.mat
plot(SNRs(:,1:20),datarate(1:20,:),'-go',...
    'LineWidth',1,...
    'MarkerSize',6,...
    'MarkerEdgeColor','k',...
    'MarkerFaceColor',[0.9,0.9,0.0]);
hold on
load Qpsk_ZF.mat
semilogy(SNRs(:,1:20),datarate(1:20,:),'-rx',...
    'LineWidth',1,...
    'MarkerSize',6,...
    'MarkerEdgeColor','k',...
    'MarkerFaceColor',[0.4,0.9,0.0]);
hold on

% load R5.mat
% semilogy(SNRs,BER_per_snr_2,'-bs',...
%     'LineWidth',1,...
%     'MarkerSize',6,...
%     'MarkerEdgeColor','k',...
%     'MarkerFaceColor',[0.9,0.0,0.0]);
% hold on

% load R5.mat
% semilogy(SNRs,BER_per_snr_2,'-rd',...
%     'LineWidth',1,...
%     'MarkerSize',6,...
%     'MarkerEdgeColor','k',...
%     'MarkerFaceColor',[0.5,0.9,0.0]);
% hold on

grid on
title('16Nta-8Nr-2Nra system ZF LS muLAW High DAC')
xlabel('SNR')
ylabel('Achievable Datarate') 
legend('8psk-ZF','Qpsk-TWH-alpha=0','Qpsk-ZF','Location','southeast');
%legend('H-DAC-u','H-DAC-nonu');