clc;
clear all;
close all;
warning off;



load 16psk_best.mat
plot(SNRs(:,1:20),datarate(1:20,:),'-b>',...
'LineWidth',1,...
'MarkerSize',6,...
'MarkerEdgeColor','k',...
'MarkerFaceColor',[0.9,0.9,0.0]);
hold on

load 8psk_best.mat
plot(SNRs(:,1:20),datarate(1:20,:),'-go',...
'LineWidth',1,...
'MarkerSize',6,...
'MarkerEdgeColor','k',...
'MarkerFaceColor',[0.9,0.9,0.0]);
hold on
load Qpsk_best.mat
semilogy(SNRs(:,1:20),datarate(1:20,:),'-rx',...
'LineWidth',1,...
'MarkerSize',6,...
'MarkerEdgeColor','k',...
'MarkerFaceColor',[0.4,0.9,0.0]);
hold on

grid on
title('32-4 system ZF muLaw high DAC')
xlabel('SNR')
ylabel('Achievable Datarate')
legend('16psk','8psk','Qpsk','Location','southeast');
%legend('H-DAC-u','H-DAC-nonu');
